trigger: none

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.18.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    skipAzureAuth: true
    validationJobs:
      - name: Run Checks
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 20
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 20
              script: npm run gen
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 20
              script: node --test
          - script: |
              git status --porcelain
              if [[ `git status --porcelain` ]]; then
                # Changes - generated files out of date! Show changes:
                git diff
                # fail pipeline run
                exit 1
              fi
            displayName: Check no generated files out of date
