trigger: none

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.10.0

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    skipAzureAuth: true
    validationJobs:
      - name: Run Checks
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 18
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 18
              script: npm run check-required
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 18
              script: npm run gen-docs
          - script: |
              git status --porcelain
              if [[ `git status --porcelain` ]]; then
                # Changes - generated files out of date!
                exit 1
              fi
            displayName: Check no generated files out of date