parameters:
  - name: dryRun
    displayName: Dry Run
    type: boolean
    default: false

trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.23.0
  pipelines:
    - pipeline: pr
      source: PR
      trigger:
        branches:
          include:
            - main

variables:
  - group: data-model-release
  - name: dryRunFlag
    ${{ if eq(parameters.dryRun, true) }}:
      value: '--dry-run'
    ${{ if eq(parameters.dryRun, false) }}:
      value: ''

pool: pins-odt-agent-pool

jobs:
  - deployment: Release
    displayName: Release
    environment: 'NPM'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 22
                script: npm ci
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 22
                script: npx semantic-release --branches main --tag-format '${version}' ${{ variables.dryRunFlag }}
                environmentVariables:
                  GH_TOKEN: $(GITHUB_TOKEN)
                  NPM_TOKEN: $(NPM_TOKEN)
    workspace:
      clean: all
