trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.18.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    skipAzureAuth: true
    validationJobs:
      - name: Tag
        steps:
          - script: |
              VERSION=$(jq -r .version package-lock.json)
              if git tag -l "$VERSION" | grep -q "$VERSION"; then
                echo "tag already exists: $VERSION"
              else
                git tag -a "$VERSION" -m "Release version $VERSION"
                git push origin "$VERSION"
              fi
        displayName: Auto git tag version with version in npm
