# generated by datamodel-codegen:
#   filename:  appeal-representation.schema.json
#   timestamp: 2024-11-04T12:51:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(Enum):
    """
    Status of the representation
    """

    awaiting_review = "awaiting_review"
    referred = "referred"
    valid = "valid"
    invalid = "invalid"
    published = "published"
    archived = "archived"
    draft = "draft"
    withdrawn = "withdrawn"
    NoneType_None = None


class Source(Enum):
    """
    Source of the representation (citizen or LPA)
    """

    lpa = "lpa"
    citizen = "citizen"
    NoneType_None = None


class RepresentationType(Enum):
    """
    The type of representation
    """

    statement = "statement"
    comment = "comment"
    final_comment = "final_comment"
    NoneType_None = None


class AppealRepresentation(BaseModel):
    """
    Schema defining the metadata for appeal representations, such as statements, third-party comments and final comments
    """

    model_config = ConfigDict(
        extra="allow",
    )
    representationId: str = Field(..., examples=["7000000-1"])
    """
    The unique identifier for the representation
    """
    caseId: int | None = Field(..., examples=[1200])
    """
    Internal case identifier
    """
    caseReference: str = Field(..., examples=["7002471"])
    """
    External case identifier
    """
    status: Status
    """
    Status of the representation
    """
    originalRepresentation: str | None = None
    """
    The original representation
    """
    redacted: bool | None = None
    """
    Indicates if the representation is redacted
    """
    redactedRepresentation: str | None = None
    """
    The redacted version of the representation
    """
    redactedBy: str | None = None
    """
    Unique identifier for the case team member that performed the redaction
    """
    invalidDetails: list[str]
    """
    A list of reasons why the representation has been marked as invalid
    """
    source: Source
    """
    Source of the representation (citizen or LPA)
    """
    representedId: str | None = None
    """
    ServiceUser Id of the person or organisation being represented
    """
    representativeId: str | None = None
    """
    ServiceUser Id of the agent representing the owner
    """
    lpaCode: str | None = None
    """
    Will only be filled if the representationType is a LPA statement
    """
    representationType: RepresentationType
    """
    The type of representation
    """
    dateReceived: AwareDatetime = Field(..., examples=["2023-07-27T20:30:00.000Z"])
    attachmentIds: list[str]
    """
    An array of documentIds
    """
