# generated by datamodel-codegen:
#   filename:  nsip-meeting.schema.json
#   timestamp: 2025-11-07T07:41:18+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PlanningInspectorateRole(Enum):
    """
    Planning Inspectorate role
    """

    facilitator = "facilitator"
    advisor = "advisor"
    observer = "observer"
    NoneType_None = None


class NsipMeeting(BaseModel):
    """
    NSIP Standalone Meeting Schema for ODW Curated layer
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caseId: int = Field(..., examples=[1242])
    """
    The unique identifier within the Back Office. This is not the same as the case reference
    """
    caseReference: str | None = Field(..., examples=["BC0510001"])
    meetingAgenda: str | None = Field(..., examples=["Flood Risk Assessment (FRA)"])
    """
    Meeting agenda
    """
    planningInspectorateRole: PlanningInspectorateRole | None = Field(
        ..., examples=["facilitator"]
    )
    """
    Planning Inspectorate role
    """
    meetingDate: AwareDatetime | None = Field(
        ..., examples=["2023-07-27T20:30:00.000Z"]
    )
    """
    Meeting date
    """
    meetingType: str | None = None
    """
    Type of Meeting
    """
