# generated by datamodel-codegen:
#   filename:  pins-lpa.schema.json
#   timestamp: 2025-05-02T11:13:19+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PinsLpa(BaseModel):
    """
    Local Planning Authority (LPA) attributes as per Horizon. This will be extended with ONS data
    """

    model_config = ConfigDict(
        extra="allow",
    )
    lpaName: str
    """
    The PINS name of the LPA
    """
    organisationType: str | None = None
    """
    The organisation type of the LPA
    """
    pinsLpaCode: str
    """
    The PINS-generated unqiue LPA code
    """
    poBox: str | None = None
    """
    LPA address Post Office Box
    """
    address1: str | None = None
    """
    First line of LPA address
    """
    address2: str | None = None
    """
    Second line of LPA address
    """
    city: str | None = None
    """
    LPA address city or town
    """
    county: str | None = None
    """
    LPA address county
    """
    postcode: str | None = None
    """
    LPA address postcode
    """
    country: str | None = None
    """
    LPA address country
    """
    telephoneNumber: str | None = None
    """
    LPA telephine number
    """
    fax: str | None = None
    """
    LPA fax number
    """
    emailAddress: str | None = None
    """
    LPA email address
    """
