# generated by datamodel-codegen:
#   filename:  pins-inspector.schema.json
#   timestamp: 2025-03-11T16:14:43+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PinsInspector(BaseModel):
    """
    Inspector attributes as per Horizon. This will be extended with SAP/Entra data
    """

    model_config = ConfigDict(
        extra="allow",
    )
    horizonId: str
    """
    The PINS-generated unique horizon ID
    """
    firstName: str
    """
    The first name of the inspector
    """
    lastName: str
    """
    The last name of the inspector
    """
    postName: str | None = None
    """
    The post name of the inspector
    """
    organisationName: str | None = None
    """
    The organisation name of the inspector
    """
    title: str | None = None
    """
    The title of the inspector
    """
    salutation: str | None = None
    """
    The salutation of the inspector
    """
    qualifications: str | None = None
    """
    The qualifications of the inspector
    """
    email: str | None = None
    """
    The email address of the inspector
    """
