# generated by datamodel-codegen:
#   filename:  application-update.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ApplicationUpdateStatus(Enum):
    """
    Application Update Status. Name displayed to users, e.g. Draft
    """

    Draft = "Draft"
    Published = "Published"
    Unpublished = "Unpublished"


class ApplicationUpdateSchema(BaseModel):
    """
    Application Update for Casework Project
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Primary key
    """
    caseReference: str | None = Field(None, examples=["CROWN/2025/12345"])
    """
    Business Key for the related case
    """
    caseId: str | None = Field(None, examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    The unique ID for the case this representation belongs to.
    """
    caseType: str | None = Field(None, examples=["Crown Development Application"])
    """
    The type of case this representation is for.
    """
    applicationUpdateStatus: ApplicationUpdateStatus | None = None
    """
    Application Update Status. Name displayed to users, e.g. Draft
    """
    details: str
    """
    Application Update text description.
    """
    firstPublished: AwareDatetime | None = None
    unpublishedDate: AwareDatetime | None = None
    lastEdited: AwareDatetime | None = None
