# generated by datamodel-codegen:
#   filename:  appeal-event-estimate.schema.json
#   timestamp: 2025-10-30T20:02:31+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AppealEventEstimate(BaseModel):
    """
    All event estimates belong to a case. A case has only one event estimate.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    """
    The unique identifier within the Back Office.
    """
    caseReference: str
    """
    The case reference the event estimate belongs to.
    """
    preparationTime: float | None = None
    """
    Estimated inspector time (days) to prepare for event.
    """
    sittingTime: float | None = None
    """
    Estimated inspector time (days) for event.
    """
    reportingTime: float | None = None
    """
    Estimated inspector time (days) for event reporting.
    """
