# generated by datamodel-codegen:
#   filename:  address.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class AddressType(Enum):
    """
    The type of thing this address is for.
    """

    site = "site"
    neighbouring = "neighbouring"
    organisation = "organisation"
    contact = "contact"


class PinsAddressSchema(BaseModel):
    """
    A schema to define the structure of an Address object in PINS.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    addressDimKey: float = Field(..., examples=[12345])
    """
    Primary Key for an Address.
    """
    addressType: AddressType | None = Field(None, examples=["site"])
    """
    The type of thing this address is for.
    """
    caseReference: str = Field(..., examples=["CROWN/2025/12345"])
    """
    Business Key for the related case
    """
    caseId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    The unique ID for the case this representation belongs to.
    """
    caseType: str = Field(..., examples=["Crown Development Application"])
    """
    The type of case this representation is for.
    """
    description: str | None = Field(None, examples=["The field behind the crown pub"])
    """
    Some sites may have a postcode, but do not have postal addresses.
    """
    line1: str | None = None
    line2: str | None = None
    townCity: str | None = None
    county: str | None = None
    postcode: str | None = None
    country: str | None = None
    easting: str | None = Field(None, examples=["358267"])
    northing: str | None = Field(None, examples=["172797"])
    latitudeWGS84: float | None = Field(None, examples=[51.452608])
    longitudeWGS84: float | None = Field(None, examples=[-2.6019821])
    UPRN: str | None = Field(None, examples=[100023336956])
    """
    The Unique Property Reference Number (UPRN) is a unique number (a geocode) for every addressable location—e.g., a building, a bus stop, a post box, a feature in the landscape, or a defibrillator—in Great Britain.
    """
    dependentRequired: Any | None = None
