# generated by datamodel-codegen:
#   filename:  applications-representation.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RepresentationStatus(Enum):
    Awaiting_review = "Awaiting review"
    Accepted = "Accepted"
    Rejected = "Rejected"
    Withdrawn = "Withdrawn"


class SubmittedFor(Enum):
    Myself = "Myself"
    On_behalf_of_another_person_or_an_organisation = (
        "On behalf of another person or an organisation"
    )


class SubmittedReceivedMethod(Enum):
    """
    How we received the representation
    """

    Online = "Online"
    Phone = "Phone"
    Email = "Email"
    Post = "Post"
    In_person = "In person"


class RepresentedType(Enum):
    """
    When representation is on behalf of a person/org/group
    """

    A_person = "A person"
    An_organisation_or_charity_I_work_or_volunteer_for = (
        "An organisation or charity I work or volunteer for"
    )
    An_organisation_or_charity_I_do_not_work_or_volunteer_for = (
        "An organisation or charity I do not work or volunteer for"
    )


class RepresentedCategory(Enum):
    Consultees = "Consultees"
    Interested_party = "Interested party"


class WithdrawalReason(Enum):
    """
    Reason for the withdrawal
    """

    Change_of_opinion = "Change of opinion"
    Mistaken_Submission = "Mistaken Submission"
    Misunderstanding = "Misunderstanding"
    Personal_Reasons = "Personal Reasons"


class ContactPreference(Enum):
    email = "email"
    post = "post"


class Contact(BaseModel):
    contactId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Source PK for Contact
    """
    contactPreference: ContactPreference | None = Field(None, examples=["email"])
    writtenRepOrgName: str | None = None
    writtenRepJobTitleorRole: str | None = None


class Status(Enum):
    """
    The status of the document
    """

    Awaiting_review = "Awaiting review"
    Accepted = "Accepted"
    Rejected = "Rejected"
    Withdrawn = "Withdrawn"


class RepresentationDocument(BaseModel):
    id: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Source Key for Representation Document
    """
    representationId: str = Field(
        ..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"]
    )
    """
    The representation this relates to
    """
    itemId: str
    """
    The id of the item in SharePoint
    """
    fileName: str
    """
    The name of the file
    """
    redactedItemId: str | None = None
    """
    The id of the redacted version of the item in sharepoint
    """
    redactedFileName: str | None = None
    """
    the name of the redacted file
    """
    status: Status
    """
    The status of the document
    """


class CaseworkRepresentationSchema(BaseModel):
    """
    Representations and related document metadata for Casework Projects
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Primary key
    """
    reference: str
    """
    Auto-generated hexadecimal reference: AAAAA-BBBBB
    """
    caseReference: str = Field(..., examples=["CROWN/2025/12345"])
    """
    Business Key for the related case
    """
    caseId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    The unique ID for the case this representation belongs to.
    """
    caseType: str = Field(..., examples=["Crown Development Application"])
    """
    The type of case this representation is for.
    """
    representationStatus: RepresentationStatus | None = None
    submittedFor: SubmittedFor
    submittedByContact: list[Contact] | None = None
    submittedByAgentFlag: bool | None = None
    submittedByAgentOrgName: str | None = None
    submittedDate: AwareDatetime
    submittedReceivedMethod: SubmittedReceivedMethod | None = None
    """
    How we received the representation
    """
    submissionMethodReason: str | None = None
    comment: str
    commentRedacted: str | None = None
    """
    redacted version of the comment, null if not redacted
    """
    representedType: RepresentedType | None = None
    """
    When representation is on behalf of a person/org/group
    """
    representedContact: list[Contact] | None = None
    """
    When representation is on behalf of a person/org/group
    """
    representedCategory: RepresentedCategory | None = None
    wantsToBeHeard: bool | None = None
    """
    Internal: wants to be heard at a hearing
    """
    containsAttachments: bool | None = None
    """
    Is a document attached to the representation
    """
    sharePointFolderCreated: bool | None = None
    """
    to avoid creating new folders for documents when managing representations
    """
    distressingContentInRepresentation: bool | None = None
    """
    Flags the representation as containing distressing content
    """
    withdrawalRequestDate: AwareDatetime | None = None
    """
    Date the representing party requested that the representation be withdrawn
    """
    withdrawalReason: WithdrawalReason | None = None
    """
    Reason for the withdrawal
    """
    dateWithdrawn: AwareDatetime | None = None
    """
    Date the representation was withdrawn
    """
    representationDocuments: list[RepresentationDocument] | None = None
