# generated by datamodel-codegen:
#   filename:  case-schedule.schema.json
#   timestamp: 2024-01-08T10:12:24+00:00

from __future__ import annotations

from pydantic import BaseModel


class CaseSchedule(BaseModel):
    pass
