# generated by datamodel-codegen:
#   filename:  pins-inspector.schema.json
#   timestamp: 2026-01-16T12:29:56+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Address(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    addressLine1: str | None = None
    addressLine2: str | None = None
    townCity: str | None = None
    county: str | None = None
    postcode: str | None = None


class Specialism(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., examples=["S62A Casework Major"])
    """
    Working above band is stored as a specialism
    """
    proficiency: str | None = Field(..., examples=["trained"])
    """
    trained or in-training
    """
    validFrom: AwareDatetime | None = Field(..., examples=["2023-07-27T20:30:00.000Z"])
    """
    Date training started or date training was completed.
    """


class PinsInspector(BaseModel):
    """
    Inspector Details originating from Horizon, SAP HR and Entra.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    entraId: str | None = Field(..., examples=["00000000-0000-0000-0000-000000000000"])
    """
    EntraID of the Inspector if available in ODW.
    """
    sapId: str | None = Field(..., examples=["12345678"])
    """
    SAPID of the Inspector if available in ODW.
    """
    horizonId: str | None = None
    """
    The PINS-generated unique horizon ID
    """
    firstName: str
    """
    The first name of the inspector
    """
    lastName: str
    """
    The last name of the inspector
    """
    postName: str | None = None
    """
    The post name of the inspector
    """
    organisationName: str | None = None
    """
    The organisation name of the inspector
    """
    title: str | None = None
    """
    The title of the inspector
    """
    salutation: str | None = None
    """
    The salutation of the inspector
    """
    qualifications: str | None = None
    """
    The qualifications of the inspector
    """
    email: EmailStr | None = Field(
        ..., examples=["example@planninginspectorate.gov.uk"]
    )
    """
    PINS Email address for the Inspector
    """
    grade: str = Field(..., examples=["B1"])
    """
    Grades as a coded value e.g. B1, B2, B3, FTC-B1, FTC-B2, FTC-B3, PL
    """
    fte: float = Field(..., examples=[0.75])
    """
    FTE Decimal value e.g. 1, 0.5 etc
    """
    unit: str = Field(..., examples=["Operations"])
    """
    The personnel area of the Inspector
    """
    service: str = Field(..., examples=["Planning and Environmental Appeals Service"])
    """
    The personnel sub area of the Inspector
    """
    group: str = Field(..., examples=["Enforcement Groups"])
    """
    Group of the Inspector
    """
    inspectorManager: str = Field(..., examples=["Dan Brown"])
    """
    Name of the Inspector's manager.
    """
    validFrom: AwareDatetime | None = Field(None, examples=["2023-07-27T20:30:00.000Z"])
    """
    Date the Inspector record was first recorded.
    """
    address: Address
    specialisms: list[Specialism]
