# generated by datamodel-codegen:
#   filename:  applications-notify-email.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class EmailStatus(Enum):
    """
    Outcome of the email (status)
    """

    Sending = "Sending"
    Delivered = "Delivered"
    Permanent_failure = "Permanent failure"
    Temporary_failure = "Temporary failure"
    Technical_failure = "Technical failure"


class ContactPreference(Enum):
    """
    Preferred contact method
    """

    email = "email"
    post = "post"


class Contact(BaseModel):
    """
    Contact the email was sent to
    """

    contactId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Source PK for Contact
    """
    contactPreference: ContactPreference | None = Field(None, examples=["email"])
    """
    Preferred contact method
    """
    writtenRepOrgName: str | None = None
    writtenRepJobTitleorRole: str | None = None


class EmailNotificationRecordSchema(BaseModel):
    """
    Email Notifications for Casework Projects
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Internal Identifier UUID
    """
    notifyId: str | None = None
    """
    Id used by Notify
    """
    reference: str | None = None
    """
    Reference passed to notify (used to identify the case or representation it relates to)
    """
    caseReference: str = Field(..., examples=["CROWN/2025/12345"])
    """
    Business Key for the related case
    """
    caseId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    The unique ID for the case this notification belongs to.
    """
    caseType: str = Field(..., examples=["Crown Development Application"])
    """
    The type of case this notification is for.
    """
    createdDate: AwareDatetime | None = None
    """
    Date the email was created
    """
    createdBy: str | None = None
    """
    Name of the person that triggered the email (only applies when done manually)
    """
    completedDate: AwareDatetime | None = None
    """
    When the email completed (succeeded or failed)
    """
    email: EmailStr | None = None
    """
    Email address sent to if unable to be linked to an LPA or Contact
    """
    contact: list[Contact] | None = None
    """
    Contact(s) the email was sent to
    """
    lpaCode: str = Field(..., examples=["Z0116"])
    """
    Planning Body code
    """
    emailStatus: EmailStatus | None = Field(None, examples=["Delivered"])
    """
    Outcome of the email (status)
    """
    templateId: str | None = None
    """
    The id of the template sent in Notify
    """
    templateVersion: int | None = None
    """
    The version of the template sent
    """
    body: str | None = None
    """
    The full HTML/plain text body of the email
    """
    subject: str | None = None
    """
    The full HTML/plain text subject of the email
    """
