# generated by datamodel-codegen:
#   filename:  nsip-invoice.schema.json
#   timestamp: 2025-11-07T07:41:18+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class InvoiceStage(Enum):
    """
    Invoice stage
    """

    pre_acceptance = "pre_acceptance"
    acceptance = "acceptance"
    pre_examination = "pre_examination"
    initial_examination = "initial_examination"
    final_examination = "final_examination"
    NoneType_None = None


class NsipInvoice(BaseModel):
    """
    NSIP Standalone Invoice Schema for ODW Curated layer
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caseId: int = Field(..., examples=[1242])
    """
    The unique identifier within the Back Office. This is not the same as the case reference
    """
    caseReference: str | None = Field(..., examples=["BC0510001"])
    invoiceStage: InvoiceStage | None = Field(..., examples=["pre_acceptance"])
    """
    Invoice stage
    """
    invoiceNumber: str = Field(..., examples=["1800004419"])
    """
    Invoice number
    """
    amountDue: float = Field(..., examples=[500])
    """
    Amount due
    """
    paymentDueDate: AwareDatetime | None = Field(
        ..., examples=["2023-07-27T20:30:00.000Z"]
    )
    """
    Payment due date
    """
    invoicedDate: AwareDatetime | None = Field(
        ..., examples=["2023-07-27T20:30:00.000Z"]
    )
    """
    Invoiced date
    """
    paymentDate: AwareDatetime | None = Field(
        ..., examples=["2023-07-27T20:30:00.000Z"]
    )
    """
    Date of payment
    """
    refundCreditNoteNumber: str | None = Field(..., examples=["1800004419"])
    """
    Refund credit note number
    """
    refundAmount: float | None = Field(..., examples=[200])
    """
    Amount refunded
    """
    refundIssueDate: AwareDatetime | None = Field(
        ..., examples=["2023-07-27T20:30:00.000Z"]
    )
    """
    Refund issue date
    """
