# generated by datamodel-codegen:
#   filename:  gettimesheets-response.schema.json
#   timestamp: 2025-01-15T15:46:26+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class GetTimesheetsApiResponse(BaseModel):
    """
    Schema defining the data returned by the DaRT API
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caseReference: int | None = Field(None, examples=["6002744"])
    """
    description
    """
    applicationReference: str | None = Field(None, examples=["12345"])
    """
    description
    """
    siteAddressLine1: str | None = Field(None, examples=["21 The Pavement"])
    """
    description
    """
    siteAddressLine2: str | None = Field(None, examples=["Shotesham Road"])
    """
    description
    """
    siteAddressTown: str | None = Field(None, examples=["Bristol"])
    """
    description
    """
    siteAddressCounty: str | None = Field(None, examples=["Wandsworth"])
    """
    description
    """
    siteAddressPostcode: str | None = Field(None, examples=["SW4 0HY"])
    """
    description
    """
