# generated by datamodel-codegen:
#   filename:  applications-application.schema.json

from __future__ import annotations

from enum import Enum, StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Type(StrEnum):
    """
    Type of application. Name displayed to users
    """

    Planning_permission = "Planning permission"
    Outline_planning_permission_with_some_matters_reserved = (
        "Outline planning permission with some matters reserved"
    )
    Outline_planning_permission_with_all_matters_reserved = (
        "Outline planning permission with all matters reserved"
    )
    Approval_of_reserved_matters_following_outline_approval = (
        "Approval of reserved matters following outline approval"
    )
    Planning_permission_and_listed_building_consent__LBC__for_alterations__extension_or_demolition_of_a_listed_building = "Planning permission and listed building consent (LBC) for alterations, extension or demolition of a listed building"


class SubType(Enum):
    """
    SubType applies to Planning permissions and LBC
    """

    Planning_permission = "Planning permission"
    Listed_building_consent__LBC_ = "Listed building consent (LBC)"


class ApplicationStatus(StrEnum):
    """
    Current status of the case (enum)
    """

    New = "New"
    Accepted = "Accepted"
    Invalid = "Invalid"
    Consultation_period_open = "Consultation period open"
    Hearing_Inquiry_date_set = "Hearing/Inquiry date set"
    Application_on_hold_awaiting_further_information = (
        "Application on hold awaiting further information"
    )
    Report_awaited = "Report awaited"
    Report_sent_to_Decision_Branch = "Report sent to Decision Branch"
    Decision_awaited = "Decision awaited"
    Decided = "Decided"
    Withdrawn = "Withdrawn"
    Declined_to_determine = "Declined to determine"
    Closed___invalid = "Closed - invalid"
    Closed___opened_in_error = "Closed - opened in error"


class ApplicationStage(Enum):
    """
    Current stage of the case (enum)
    """

    Accepted = "Accepted"
    Consultation = "Consultation"
    Procedure_choice = "Procedure choice"
    Written_representations = "Written representations"
    Inquiry = "Inquiry"
    Hearing_Inquiry_date_set = "Hearing/Inquiry date set"
    Final_decision = "Final decision"


class Category(Enum):
    """
    Application category (enum)
    """

    Major_Development = "Major Development"
    Buildings_over_1000_square_metres = "Buildings over 1000 square metres"
    Development_of_a_site_above_1_hectare = "Development of a site above 1 hectare"
    Dwellings_numbering_10_or_more = "Dwellings numbering 10 or more"
    Dwellings_of_0_5_hectare_or_more = "Dwellings of 0.5 hectare or more"
    Minerals = "Minerals"
    Waste = "Waste"
    Non_Major_Development = "Non-Major Development"
    Buildings_less_than_1000_square_metres = "Buildings less than 1000 square metres"
    Development_of_a_site_less_than_1_hectare = (
        "Development of a site less than 1 hectare"
    )
    Dwellings_numbering_between_1_and_9 = "Dwellings numbering between 1 and 9"
    Dwellings_of_less_than_0_5_hectare = "Dwellings of less than 0.5 hectare"
    Change_of_use = "Change of use"
    Relevant_demolition = "Relevant demolition"
    Other = "Other"
    Listed_building_consent_to_alter_extend = "Listed building consent to alter/extend"
    Listed_building_consent_to_demolish = "Listed building consent to demolish"


class DecisionOutcome(Enum):
    """
    As displayed to users
    """

    Approved = "Approved"
    Approved_with_conditions = "Approved with conditions"
    Refused = "Refused"
    Withdrawn = "Withdrawn"


class EiaScreeningOutcome(Enum):
    """
    What was the outcome of the Environmental Impact Assessment
    """

    required = "required"
    not_required = "not required"


class Procedure(Enum):
    """
    Name displayed to users
    """

    Written_Representations = "Written Representations"
    Hearing = "Hearing"
    Inquiry = "Inquiry"


class RoleType(StrEnum):
    """
    Agent or Applicant details
    """

    agent = "agent"
    applicant = "applicant"


class ContactPreference(Enum):
    email = "email"
    post = "post"


class Contact(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    contactId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Source PK for Contact
    """
    contactPreference: ContactPreference | None = Field(None, examples=["email"])
    writtenRepOrgName: str | None = None
    """
    Organisation Name used for written-representation on behalf of an organisation
    """
    writtenRepJobTitleorRole: str | None = None
    """
    Job Title or Role used for written-representation on behalf of an organisation
    """


class Address(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    line1: str | None = None
    line2: str | None = None
    townCity: str | None = None
    county: str | None = None
    postcode: str


class Organisation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    roleType: RoleType | None = Field(None, examples=["agent"])
    """
    Agent or Applicant details
    """
    organisationId: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Source PK for Organisation
    """
    organisationName: str | None = None
    organisationAddress: list[Address] | None = None
    contacts: list[Contact] | None = None
    """
    An Organisation may be linked to one or more Contacts
    """


class CrownDevelopmentApplication(BaseModel):
    """
    Main application details for Crown Development Project
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"])
    """
    Internal Identifier UUID
    """
    reference: str = Field(..., examples=["CROWN/2025/12345"])
    """
    External Identifier: CROWN/YYYY/XXXXXXX
    """
    createdDate: AwareDatetime
    """
    Date the case was created
    """
    updatedDate: AwareDatetime | None = None
    """
    Date the case was updated
    """
    type: Type = Field(
        ..., examples=["Outline planning permission with some matters reserved"]
    )
    """
    Type of application. Name displayed to users
    """
    subType: SubType | None = Field(None, examples=["Listed building consent (LBC)"])
    """
    SubType applies to Planning permissions and LBC
    """
    linkedParentId: str | None = Field(
        None, examples=["AAAAAAAA-1234-1234-1234-AAAAAAAAAAAA"]
    )
    """
    Self-referencial for parent to children relationship
    """
    description: str | None = None
    """
    Description of the project
    """
    primaryLPACode: str | None = Field(None, examples=["Z0116"])
    """
    Primary Planning Body code
    """
    secondaryLPACode: str | None = Field(None, examples=["Z0116"])
    """
    Secondary LPAs when project overlaps authorities
    """
    hasAgent: bool
    """
    Is an agent assigned to the case on behalf of the applicant
    """
    organisations: list[Organisation] | None = None
    """
    Applications can have one or more organisaitons associated with them.
    """
    siteAddress: list[Address] | None = None
    """
    Site Address details
    """
    siteEasting: str | None = Field(None, examples=["216600"])
    """
    Easting of the site, if known
    """
    siteNorthing: str | None = Field(None, examples=["771200"])
    """
    Northing of the site, if known
    """
    siteArea: float | None = Field(None, examples=[4.44])
    """
    Site area in hectares
    """
    expectedDateOfSubmission: AwareDatetime | None = None
    """
    Date case officer expects the application to be submitted (NB: cases are created before document submissions as applicants upload directly)
    """
    applicationStatus: ApplicationStatus | None = None
    """
    Current status of the case (enum)
    """
    applicationStage: ApplicationStage | None = None
    """
    Current stage of the case (enum)
    """
    nationallyImportant: bool | None = None
    """
    Site is nationally important (Yes/No)
    """
    nationallyImportantConfirmationDate: AwareDatetime | None = None
    """
    Date the application's national importance was confirmed
    """
    notNationallyImportantEmailSent: bool | None = None
    """
    Flags if a notNationallyImportant email has been sent
    """
    containsDistressingContent: bool | None = None
    """
    Highlights the cases as containing distressing content
    """
    lpaReference: str | None = None
    """
    LPA cross reference. Reference number for the case as known by the Local Planning Authority (LPA)
    """
    category: Category | None = None
    """
    Application category (enum)
    """
    isGreenBelt: bool | None = None
    """
    Is the site in green belt land
    """
    healthAndSafetyIssue: bool | None = None
    """
    Does the Site has H&S Issue
    """
    applicationReceivedDate: AwareDatetime | None = None
    """
    Date the application was received
    """
    applicationReceivedDateEmailSent: bool | None = None
    """
    Flags if an applicationReceived email has been sent
    """
    applicationAcceptedDate: AwareDatetime | None = None
    """
    Date the application was accepted
    """
    lpaQuestionnaireSentDate: AwareDatetime | None = None
    """
    Date the lpa questionnaire was sent
    """
    lpaQuestionnaireReceivedDate: AwareDatetime | None = None
    """
    Date the lpa questionnaire was received
    """
    lpaQuestionnaireReceivedEmailSent: bool | None = None
    """
    Flags if an lpaQuestionnaireReceived email has been sent
    """
    publishDate: AwareDatetime | None = None
    """
    Date the application was published to the portal
    """
    pressNoticeDate: AwareDatetime | None = None
    """
    Date the press notice was published
    """
    neighboursNotifiedByLpaDate: AwareDatetime | None = None
    """
    Date the neighbours were notified by the LPA
    """
    siteNoticeByLpaDate: AwareDatetime | None = None
    """
    Date the site notice was erected by the LPA
    """
    targetDecisionDate: AwareDatetime | None = None
    """
    Date the application should be decided by
    """
    extendedTargetDecisionDate: AwareDatetime | None = None
    """
    Extended date by which the application should be decided
    """
    recoveredDate: AwareDatetime | None = None
    """
    Date the application was recovered by the Secretary of State
    """
    recoveredReportSentDate: AwareDatetime | None = None
    """
    Date the Inspector's report was sent to the Secretary of State
    """
    withdrawnDate: AwareDatetime | None = None
    """
    Date application was withdrawn
    """
    decisionDate: AwareDatetime | None = None
    """
    Date the application was decided on
    """
    originalDecisionDate: AwareDatetime | None = None
    """
    Date of the original decision if later quashed
    """
    decisionOutcome: DecisionOutcome | None = None
    """
    As displayed to users
    """
    turnedAwayDate: AwareDatetime | None = None
    """
    Date application was turned away
    """
    representationsPublishDate: AwareDatetime | None = None
    """
    Date the representations was publish
    """
    representationsPeriodStartDate: AwareDatetime | None = None
    """
    Start date of the representation period (starts at 00:00)
    """
    representationsPeriodEndDate: AwareDatetime | None = None
    """
    End date of the representation period (ends at 23:59)
    """
    inspector1Id: str | None = None
    """
    EntraID for Inspector
    """
    inspector2Id: str | None = None
    """
    EntraID for Inspector
    """
    inspector3Id: str | None = None
    """
    EntraID for Inspector
    """
    assessorInspectorId: str | None = None
    """
    EntraID for Assessor
    """
    caseOfficerId: str | None = None
    """
    EntraID for Case Officer
    """
    planningOfficerId: str | None = None
    """
    EntraID for Planning Officer
    """
    eiaScreening: bool | None = None
    """
    Does the application need an Environmental Impact Assessment
    """
    eiaScreeningOutcome: EiaScreeningOutcome | None = None
    """
    What was the outcome of the Environmental Impact Assessment
    """
    environmentalStatementReceivedDate: AwareDatetime | None = None
    """
    Date the environmental statement was received
    """
    siteIsVisibleFromPublicLand: bool | None = None
    """
    Site is visible from public land (Yes/No or TRUE/FALSE tbc)
    """
    procedure: Procedure | None = None
    """
    Name displayed to users
    """
    procedureNotificationDate: AwareDatetime | None = None
    eventDate: AwareDatetime | None = None
    eventPrepDuration: float | None = Field(None, examples=[1234.56])
    eventSittingDuration: float | None = Field(None, examples=[1234.56])
    eventReportingDuration: float | None = Field(None, examples=[1234.56])
    eventVenue: str | None = None
    eventNotificationDate: AwareDatetime | None = None
    eventIssuesReportPublishedDate: AwareDatetime | None = None
    eventStatementsDate: AwareDatetime | None = None
    eventCaseManagementConferenceDate: AwareDatetime | None = None
    eventPreMeetingDate: AwareDatetime | None = None
    eventProofsOfEvidenceDate: AwareDatetime | None = None
    hasApplicationFee: bool | None = None
    """
    Application has associated Fee (Yes/No or TRUE/FALSE tbc)
    """
    applicationFee: float | None = None
    """
    The amount to be payed by the Applicant
    """
    applicationFeeReceivedDate: AwareDatetime | None = None
    """
    Date the application fee was received
    """
    eligibleForFeeRefund: bool | None = None
    """
    Is the applicant eligible for a refund on the fee
    """
    applicationFeeRefundAmount: float | None = None
    """
    The amount to be refunded to the Applicant
    """
    applicationFeeRefundDate: AwareDatetime | None = None
    """
    Date the application fee was refunded
    """
    siteVisitDate: AwareDatetime | None = None
    """
    Date the site was/is going to be visited by the inspector
    """
    cilLiable: bool | None = None
    """
    Is the application liable for a community infrastructure levy
    """
    cilAmount: float | None = None
    """
    The amount for the community infrastructure levy
    """
    bngExempt: bool | None = None
    """
    Is the site exempt from the Biodiversity Net Gain
    """
    hasCostsApplications: bool | None = None
    """
    If a party is making a cost claim against another for unreasonable behaviour
    """
    costsApplicationsComment: str | None = None
    """
    Details about the cost application
    """
    environmentalImpactAssessment: bool | None = None
    """
    Does the application have an Environmental Impact Assessment - used for context in emails to LPAs
    """
    developmentPlan: bool | None = None
    """
    Is the application a standard development plan - used for context in emails to LPAs
    """
    rightOfWay: bool | None = None
    """
    Does the application apply to rights of way - used for context in emails to LPAs
    """
