# generated by datamodel-codegen:
#   filename:  dart-response.schema.json
#   timestamp: 2025-01-15T16:23:48+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class DartApiResponse(BaseModel):
    """
    Schema defining the data returned by the DaRT API
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caseId: int | None = Field(None, examples=["2744"])
    """
    description
    """
    caseReference: int | None = Field(None, examples=["6002744"])
    """
    description
    """
    caseStatus: str | None = Field(None, examples=["lpa_questionnaire"])
    """
    description
    """
    caseType: str | None = Field(None, examples=["w"])
    """
    description
    """
    caseProcedure: str | None = Field(None, examples=["W"])
    """
    description
    """
    lpaCode: str | None = Field(None, examples=["DORS"])
    """
    description
    """
    lpaName: str | None = Field(None, examples=["example"])
    """
    description
    """
    allocationLevel: str | None = Field(None, examples=["H"])
    """
    description
    """
    allocationBand: int | None = Field(None, examples=["1"])
    """
    description
    """
    caseSpecialisms: list | None = Field(
        None, examples=["General allocation", "Housing orders", "Waste"]
    )
    """
    description
    """
    caseSubmittedDate: str | None = Field(None, examples=["025-01-02T16:20:07.753Z"])
    """
    description
    """
    caseCreatedDate: str | None = Field(None, examples=["025-01-02T16:20:07.753Z"])
    """
    description
    """
    caseUpdatedDate: str | None = Field(None, examples=["025-01-02T16:20:07.753Z"])
    """
    description
    """
    caseValidDate: str | None = Field(None, examples=["025-01-02T16:20:07.753Z"])
    """
    description
    """
    caseValidationDate: str | None = Field(None, examples=["025-01-02T16:20:07.753Z"])
    """
    description
    """
    caseValidationOutcome: str | None = Field(None, examples=["valid"])
    """
    description
    """
    caseValidationInvalidDetails: list | None = Field(
        None,
        examples=[
            "Appeal has not been submitted on time",
            "Documents have not been submitted on time",
            "Other: scddsfv",
        ],
    )
    """
    description
    """
    caseValidationIncompleteDetails: list | None = Field(
        None,
        examples=[
            "Duis sunt ut in voluptate",
            "nulla proident tempor do Ut",
            "Excepteur et ut",
            "dolore elit",
            "elit adipisicing exercitation",
        ],
    )
    """
    description
    """
    caseExtensionDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    caseStartedDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    casePublishedDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    linkedCaseStatus: str | None = Field(None, examples=["child"])
    """
    description
    """
    leadCaseReference: str | None = Field(None, examples=["6002745"])
    """
    description
    """
    caseWithdrawnDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    caseTransferredDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    transferredCaseClosedDate: str | None = Field(
        None, examples=["2025-01-10T00:00:00.000Z"]
    )
    """
    description
    """
    caseDecisionOutcomeDate: str | None = Field(
        None, examples=["2025-01-10T00:00:00.000Z"]
    )
    """
    description
    """
    caseDecisionPublishedDate: str | None = Field(
        None, examples=["2025-01-10T00:00:00.000Z"]
    )
    """
    description
    """
    caseDecisionOutcome: str | None = Field(None, examples=["allowed"])
    """
    description
    """
    caseCompletedDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    enforcementNotice: str | None = Field(None, examples=["example"])
    """
    description
    """
    applicationReference: str | None = Field(None, examples=["21824/APP/0/203130"])
    """
    description
    """
    applicationDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    applicationDecision: str | None = Field(None, examples=["refused"])
    """
    description
    """
    lpaDecisionDate: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    caseSubmissionDueDate: str | None = Field(
        None, examples=["2025-01-10T00:00:00.000Z"]
    )
    """
    description
    """
    siteAddressLine1: str | None = Field(None, examples=["21 The Pavement"])
    """
    description
    """
    siteAddressLine2: str | None = Field(None, examples=["Shotesham Road"])
    """
    description
    """
    siteAddressTown: str | None = Field(None, examples=["Bristol"])
    """
    description
    """
    siteAddressCounty: str | None = Field(None, examples=["Wandsworth"])
    """
    description
    """
    siteAddressPostcode: str | None = Field(None, examples=["SW4 0HY"])
    """
    description
    """
    isCorrectAppealType: bool | None = Field(None, examples=["True"])
    """
    description
    """
    originalDevelopmentDescription: str | None = Field(
        None, examples=["mollit esse ipsum"]
    )
    """
    description
    """
    changedDevelopmentDescription: bool | None = Field(None, examples=["True"])
    """
    description
    """
    newConditionDetails: str | None = Field(None, examples=["example"])
    """
    description
    """
    nearbyCaseReferences: list | None = Field(
        None, examples=["123", "456", "678", "789"]
    )
    """
    description
    """
    neighbouringSiteAddresses: list | None = Field(
        None,
        examples=[
            {
                "neighbouringSiteAddressLine1": "officia qui",
                "neighbouringSiteAddressLine2": "ea ipsum",
                "neighbouringSiteAddressTown": "culpa mollit eu",
                "neighbouringSiteAddressCounty": "do voluptate",
                "neighbouringSiteAddressPostcode": "proident dolore sit cillum",
                "neighbouringSiteSafetyDetails": "ullamco veniam nostrud",
            },
            {
                "neighbouringSiteAddressLine1": "dolore aliqua fugiat quis commodo",
                "neighbouringSiteAddressLine2": "minim nisi in eu ut",
                "neighbouringSiteAddressTown": "non aute",
                "neighbouringSiteAddressPostcode": "eiusmod",
                "neighbouringSiteAccessDetails": "non",
            },
            {
                "neighbouringSiteAddressLine1": "ut dolore Ut eu est",
                "neighbouringSiteAddressLine2": "ea eiusmod nostrud pariatur esse",
                "neighbouringSiteAddressTown": "nulla qui aliqua",
                "neighbouringSiteAddressPostcode": "fugiat Ut labore",
                "neighbouringSiteAccessDetails": "quis pariatur est",
            },
            {
                "neighbouringSiteAddressLine1": "do laboris Ut",
                "neighbouringSiteAddressLine2": "cillum Ut",
                "neighbouringSiteAddressTown": "consectetur occaecat eiusmod sit",
                "neighbouringSiteAddressCounty": "ex tempor irure",
                "neighbouringSiteAddressPostcode": "ea Excepteur",
                "neighbouringSiteSafetyDetails": "Ut qui voluptate",
            },
        ],
    )
    """
    description
    """
    affectedListedBuildingNumbers: list | None = Field(
        None, examples=["1202152", "1356318"]
    )
    """
    description
    """
    appellantCostsAppliedFor: bool | None = Field(None, examples=["True"])
    """
    description
    """
    lpaCostsAppliedFor: bool | None = Field(None, examples=["False"])
    """
    description
    """
    appellantName: str | None = Field(None, examples=["example"])
    """
    description
    """
    typeOfEvent: str | None = Field(None, examples=["example"])
    """
    description
    """
    startDateOfTheEvent: str | None = Field(None, examples=["2025-01-10T00:00:00.000Z"])
    """
    description
    """
    inspectorName: str | None = Field(None, examples=["example"])
    """
    description
    """
    caseOfficerName: str | None = Field(None, examples=["example"])
    """
    description
    """
    inspectorQualifications: str | None = Field(None, examples=["example"])
    """
    description
    """
